<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;

class RegisterTest extends TestCase
{
    use DatabaseMigrations;


    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        \Artisan::call('passport:install');
    }

    /** @test */
    function it_should_be_register_an_user()
    {
        $response = $this->json('POST', 'api/register', [
            'name' => 'HaroldV',
            'email' => 'harold@test.com',
            'password' => 'secret',
            'c_password' => 'secret'
        ]);

        $response
            ->assertJson(['success'=> true]);

    }

    /** @test */
    function it_should_cannot_register_by_different_passwords()
    {
        $response = $this->json('POST', 'api/register', [
            'name' => 'HaroldV',
            'email' => 'harold@test.com',
            'password' => 'secret',
            'c_password' => 'secreta'
        ]);

        $response
            ->assertJson([
                'success' => false
            ]);
    }

}
